/**
 * PRESETS NARRATIVOS ESTRUCTURADOS TGP V2
 * 8 Modos narrativos con configuraciones visuales tipadas, campos desaconsejados y prohibidos.
 */

import type { NarrativeMode, NarrativePreset } from './types';

export const NARRATIVE_PRESETS: Record<Exclude<NarrativeMode, 'auto'>, NarrativePreset> = {
  'observational-drama': {
    id: 'observational-drama',
    label: 'Drama Observacional',
    description: 'Escena natural, cámara testigo, gesto contenido, luz motivada.',
    preferred: {
      subjectTreatment: 'observational-human',
      environment: 'lived-historic-interior',
      humanTrace: 'working-figure',
      shotScale: 'medium',
      cameraAngle: 'eye-level',
      cameraPosition: 'distant-witness',
      lensCharacter: 'documentary-35mm',
      focusStrategy: 'zone-focus',
      primaryComposition: 'asymmetric-balance',
      lightingSource: 'overcast-daylight',
      lightingQuality: 'soft-wrap',
      colorPalette: 'neutral-archive',
      captureMedium: '35mm-color-negative',
      filmTreatment: 'clean-daylight-negative',
      materiality: ['worn-velvet', 'waxed-wood', 'skin-fabric'],
      imperfectionLevel: 'human',
      requestedAspectProfile: 'article-3-2',
      selectedNegativeConstraints: ['no-excessive-bokeh', 'no-orange-teal', 'no-plastic-skin'],
    },
    discouraged: {
      shotScale: ['macro-detail', 'extreme-close'],
      lightingQuality: ['specular-editorial', 'flat-forensic'],
    },
    forbidden: {
      selectedNegativeConstraints: [],
    },
    priorityNotes: [
      'Gesto contenido sin sobreactuación',
      'Luz natural motivada por aperturas reales de la arquitectura',
      'Cámara como testigo silencioso a la altura de los ojos',
    ],
  },

  'historical-epic': {
    id: 'historical-epic',
    label: 'Épica Histórica',
    description: 'Escala territorial o arquitectónica, profundidad y figuras de escala.',
    preferred: {
      subjectTreatment: 'environmental-subject',
      environment: 'monumental-landscape',
      humanTrace: 'distant-scale',
      shotScale: 'extreme-wide',
      cameraAngle: 'low-angle',
      cameraPosition: 'distant-witness',
      lensCharacter: 'large-format-precise',
      focusStrategy: 'deep-focus',
      primaryComposition: 'environmental-scale',
      secondaryComposition: 'layered-depth',
      lightingSource: 'raking-sun',
      lightingQuality: 'hard-raking',
      colorPalette: 'mineral-cool',
      captureMedium: 'digital-cinema-large-format',
      filmTreatment: 'soft-print-film',
      materiality: ['dry-stone', 'mud-clay', 'salt-air'],
      imperfectionLevel: 'raw-documentary',
      requestedAspectProfile: 'hero-16-9',
      selectedNegativeConstraints: ['no-decorative-ruins', 'no-tourist-postcard', 'no-empty-cinematic-spectacle'],
    },
    discouraged: {
      shotScale: ['close', 'extreme-close', 'macro-detail'],
      focusStrategy: ['shallow-controlled'],
    },
    forbidden: {
      shotScale: ['macro-detail', 'extreme-close'],
    },
    priorityNotes: [
      'El paisaje y la masa geológica/arquitectónica dominan el encuadre',
      'Figuras humanas presentes solo como escala para magnificar el entorno',
      'Profundidad de campo profunda para mantener legibles todas las capas',
    ],
  },

  'psychological-closeup': {
    id: 'psychological-closeup',
    label: 'Primer Plano Psicológico',
    description: 'Rostro, manos, objeto íntimo o gesto concentrado; fondo subordinado.',
    preferred: {
      subjectTreatment: 'editorial-portrait',
      environment: 'lived-historic-interior',
      humanTrace: 'hands-only',
      shotScale: 'close',
      cameraAngle: 'eye-level',
      cameraPosition: 'intimate-near',
      lensCharacter: 'medium-format-natural',
      focusStrategy: 'selective-focus',
      primaryComposition: 'asymmetric-balance',
      lightingSource: 'tungsten-practical',
      lightingQuality: 'restrained-chiaroscuro',
      colorPalette: 'tungsten-neutral',
      captureMedium: 'medium-format-6x7',
      filmTreatment: 'balanced-tungsten-negative',
      materiality: ['skin-fabric', 'worn-velvet', 'aged-paper'],
      imperfectionLevel: 'human',
      requestedAspectProfile: 'editorial-4-5',
      selectedNegativeConstraints: ['no-plastic-skin', 'no-excessive-bokeh', 'no-orange-teal'],
    },
    discouraged: {
      shotScale: ['wide', 'extreme-wide'],
      primaryComposition: ['environmental-scale'],
    },
    forbidden: {
      shotScale: ['extreme-wide'],
    },
    priorityNotes: [
      'Atención visceral en el micro-gesto, textura de piel o manipulación',
      'Fondo subordinado en sombra o caída suave de foco',
      'Claroscuro sobrio sin estridencias digitales',
    ],
  },

  'night-expedition': {
    id: 'night-expedition',
    label: 'Expedición Nocturna',
    description: 'Oscuridad realista, fuentes prácticas limitadas y orientación espacial legible.',
    preferred: {
      subjectTreatment: 'evidential-object',
      environment: 'nocturnal-site',
      humanTrace: 'hands-only',
      shotScale: 'medium-wide',
      cameraAngle: 'eye-level',
      cameraPosition: 'threshold-doorway',
      lensCharacter: 'spherical-vintage-low-contrast',
      focusStrategy: 'gradual-falloff',
      primaryComposition: 'corridor-framing',
      lightingSource: 'candle-fire',
      lightingQuality: 'low-key-motivated',
      colorPalette: 'sodium-cyan-night',
      captureMedium: '35mm-color-negative',
      filmTreatment: 'high-speed-tungsten-grain',
      materiality: ['wet-stone', 'smoke-soot', 'oxidized-metal'],
      imperfectionLevel: 'raw-documentary',
      requestedAspectProfile: 'hero-16-9',
      selectedNegativeConstraints: ['no-blue-anamorphic-flare', 'no-glowing-symbols', 'no-floating-particles'],
    },
    discouraged: {
      lightingSource: ['golden-hour', 'raking-sun', 'overcast-daylight'],
      filmTreatment: ['clean-daylight-negative', 'kodachrome-inspired'],
    },
    forbidden: {
      lightingSource: ['golden-hour', 'raking-sun', 'hard-sun'],
    },
    priorityNotes: [
      'Oscuridad física real: las fuentes prácticas solo iluminan su radio verosímil',
      'Sombras densas pero con textura mineral y relieve reconocible',
      'Grano de alta sensibilidad o atmósfera nocturna auténtica',
    ],
  },

  'archival-reconstruction': {
    id: 'archival-reconstruction',
    label: 'Reconstrucción de Archivo',
    description: 'Reconstrucción documental, contenida, precisa y poco espectacularizada.',
    preferred: {
      subjectTreatment: 'archival-tableau',
      environment: 'institutional-archive',
      humanTrace: 'abandoned-tools',
      shotScale: 'medium-close',
      cameraAngle: 'architectural-frontal',
      cameraPosition: 'centered-observer',
      lensCharacter: 'large-format-precise',
      focusStrategy: 'deep-focus',
      primaryComposition: 'formal-tableau',
      lightingSource: 'overcast-daylight',
      lightingQuality: 'flat-forensic',
      colorPalette: 'neutral-archive',
      captureMedium: 'large-format-sheet-film',
      filmTreatment: 'archival-fade',
      materiality: ['aged-paper', 'waxed-wood', 'light-dust', 'oxidized-metal'],
      imperfectionLevel: 'archival-distress',
      requestedAspectProfile: 'article-3-2',
      selectedNegativeConstraints: ['no-generic-dark-academia', 'no-unmotivated-volumetric-dust', 'no-steampunk'],
    },
    discouraged: {
      cameraAngle: ['subtle-dutch'],
      lightingQuality: ['specular-editorial'],
    },
    forbidden: {},
    priorityNotes: [
      'Organización geométrica y rigurosa de documentos y herramientas',
      'Luz plana o envolvente de archivo funcional, no biblioteca gótica efectista',
      'Micro-texturas de celulosa, cuero y óxido preservadas en alta definición',
    ],
  },

  'field-documentary': {
    id: 'field-documentary',
    label: 'Documental de Campo',
    description: 'Terreno, clima, evidencia material, trabajo humano y luz encontrada.',
    preferred: {
      subjectTreatment: 'landscape-as-evidence',
      environment: 'archaeological-field',
      humanTrace: 'working-figure',
      shotScale: 'wide',
      cameraAngle: 'eye-level',
      cameraPosition: 'off-axis',
      lensCharacter: 'documentary-35mm',
      focusStrategy: 'zone-focus',
      primaryComposition: 'layered-depth',
      lightingSource: 'overcast-daylight',
      lightingQuality: 'ambient-unbeautified',
      colorPalette: 'wet-earth',
      captureMedium: '35mm-color-negative',
      filmTreatment: 'kodachrome-inspired',
      materiality: ['mud-clay', 'dry-stone', 'salt-air', 'skin-fabric'],
      imperfectionLevel: 'raw-documentary',
      requestedAspectProfile: 'article-3-2',
      selectedNegativeConstraints: ['no-tourist-postcard', 'no-plastic-skin', 'no-over-sharpening'],
    },
    discouraged: {
      lightingQuality: ['specular-editorial', 'restrained-chiaroscuro'],
      imperfectionLevel: ['pristine-editorial'],
    },
    forbidden: {},
    priorityNotes: [
      'Clima tangible: viento, polvo, barro o humedad en superficie',
      'Cámara en mano o trípode de campo a la intemperie',
      'Luz encontrada sin reflectores artificiales ni retoques estéticos',
    ],
  },

  'editorial-relic': {
    id: 'editorial-relic',
    label: 'Reliquia Editorial',
    description: 'Objeto como protagonista editorial, con escala, sombra, textura y espacio negativo.',
    preferred: {
      subjectTreatment: 'evidential-object',
      environment: 'museum-clinical',
      humanTrace: 'none',
      shotScale: 'macro-detail',
      cameraAngle: 'three-quarter',
      cameraPosition: 'intimate-near',
      lensCharacter: 'macro-flat-field',
      focusStrategy: 'selective-focus',
      primaryComposition: 'negative-space-for-title',
      secondaryComposition: 'asymmetric-balance',
      lightingSource: 'museum-led',
      lightingQuality: 'specular-editorial',
      colorPalette: 'mineral-cool',
      captureMedium: 'digital-medium-format',
      filmTreatment: 'restrained-bleach-bypass',
      materiality: ['oxidized-metal', 'bone-ivory', 'pigment-fresco', 'dry-stone'],
      imperfectionLevel: 'restrained',
      requestedAspectProfile: 'hero-16-9',
      selectedNegativeConstraints: ['no-floating-particles', 'no-glowing-symbols', 'no-unmotivated-volumetric-dust'],
    },
    discouraged: {
      shotScale: ['extreme-wide', 'wide'],
      environment: ['monumental-landscape'],
    },
    forbidden: {},
    priorityNotes: [
      'El objeto histórico ocupa la jerarquía visual absoluta con micro-texturas nítidas',
      'Espacio negativo reservado deliberadamente para diagramación o títulos',
      'Sombra arrojada limpia y soporte material de conservación sobrio',
    ],
  },

  'material-surrealism': {
    id: 'material-surrealism',
    label: 'Surrealismo Material',
    description: 'Mundo realista con una única anomalía material o causal.',
    preferred: {
      subjectTreatment: 'material-anomaly',
      environment: 'monumental-landscape',
      humanTrace: 'distant-scale',
      shotScale: 'medium-wide',
      cameraAngle: 'eye-level',
      cameraPosition: 'centered-observer',
      lensCharacter: 'medium-format-natural',
      focusStrategy: 'deep-focus',
      primaryComposition: 'central-iconic',
      secondaryComposition: 'layered-depth',
      lightingSource: 'overcast-daylight',
      lightingQuality: 'soft-wrap',
      colorPalette: 'mineral-cool',
      captureMedium: 'digital-cinema-large-format',
      filmTreatment: 'restrained-bleach-bypass',
      materiality: ['dry-stone', 'oxidized-metal', 'glass-steel'],
      imperfectionLevel: 'human',
      requestedAspectProfile: 'hero-16-9',
      selectedNegativeConstraints: ['no-fantasy-costume', 'no-glowing-symbols', 'no-floating-particles', 'no-steampunk'],
    },
    discouraged: {
      imperfectionLevel: ['archival-distress'],
    },
    forbidden: {},
    priorityNotes: [
      'Exactamente UNA anomalía material en un entorno fotográficamente sobrio y verídico',
      'La física de la luz, el grano y las sombras deben ser impecablemente reales',
      'Evitar estética de fantasía, brillos mágicos o clichés de ciencia ficción',
    ],
  },
};

export function getPresetByMode(mode: NarrativeMode): NarrativePreset | null {
  if (mode === 'auto') return null;
  return NARRATIVE_PRESETS[mode] || null;
}
